apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-container
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fabiomattes2016/Teste-Infra-Estrutura-Big-Data.git
    path: helm/notebook-container
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: 'in-cluster'
    namespace: notebook
    server: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true