annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: v0.7.4
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: A management console for minio server and operator
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/minio-console
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- minio-console
- minio
- s3
kubeVersion: '>=1.16.0-0'
maintainers:
- email: cubic@coldice.net
  name: cubic3d
name: minio-console
sources:
- https://github.com/minio/console
version: 2.4.2
